name: deploy-pwa-erp-solutions

on:
  push:
    branches:
      - aws
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete --exclude '*.html' --exclude '*.txt' --exclude '*.json' --exclude '*.xml' . s3://newpamss3/latest/
        env:
          AWS_S3_BUCKET: ${{ AWS_S#_BUCKET_NAME }}
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build/    
